# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: qnkxsovc ⇔ gdaniels
email: qnkxsovc@gmail.com
email_str: qnkxsovc {at} gmail {dot} com
description: >- # this means to ignore newlines until "baseurl:"
  This is a blog for my projects. Qnkxsovc is Gdaniels in ROT 10.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://qnkxsovc.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: qnkxsovc
github_username:  qnkxsovc
linkedin_username: qnkxsovc

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
theme: minima

plugins:
  - jekyll-seo-tag
  - jekyll-email-protect
  - jekyll-feed